name: lgapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - asset/fonts/

  fonts:
    - family: Cabin
      fonts:
        - asset: "asset/fonts/Cabin/static/Cabin_Condensed-MediumItalic.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_Condensed-Regular.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_Condensed-SemiBold.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_Condensed-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_SemiCondensed-Bold.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_SemiCondensed-BoldItalic.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_SemiCondensed-Italic.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_SemiCondensed-Medium.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_SemiCondensed-MediumItalic.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_SemiCondensed-Regular.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_SemiCondensed-SemiBold.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_SemiCondensed-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin-Bold.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin-BoldItalic.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin-Italic.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin-Medium.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin-MediumItalic.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin-Regular.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin-SemiBold.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_Condensed-Bold.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_Condensed-BoldItalic.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_Condensed-Italic.ttf"
        - asset: "asset/fonts/Cabin/static/Cabin_Condensed-Medium.ttf"
    - family: Lato
      fonts:
        - asset: "asset/fonts/Lato/Lato-ThinItalic.ttf"
        - asset: "asset/fonts/Lato/Lato-Black.ttf"
        - asset: "asset/fonts/Lato/Lato-BlackItalic.ttf"
        - asset: "asset/fonts/Lato/Lato-Bold.ttf"
        - asset: "asset/fonts/Lato/Lato-BoldItalic.ttf"
        - asset: "asset/fonts/Lato/Lato-Italic.ttf"
        - asset: "asset/fonts/Lato/Lato-Light.ttf"
        - asset: "asset/fonts/Lato/Lato-LightItalic.ttf"
        - asset: "asset/fonts/Lato/Lato-Regular.ttf"
        - asset: "asset/fonts/Lato/Lato-Thin.ttf"
    - family: Montserrat
      fonts:
        - asset: "asset/fonts/Montserrat/static/Montserrat-ThinItalic.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-Black.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-BlackItalic.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-Bold.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-BoldItalic.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-ExtraBold.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-ExtraBoldItalic.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-ExtraLight.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-ExtraLightItalic.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-Italic.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-Light.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-LightItalic.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-Medium.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-MediumItalic.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-Regular.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-SemiBold.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Montserrat/static/Montserrat-Thin.ttf"

    - family: Mulish
      fonts:
        - asset: "asset/fonts/Mulish/static/Mulish-BoldItalic.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-ExtraBold.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-ExtraBoldItalic.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-ExtraLight.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-ExtraLightItalic.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-Italic.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-Light.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-LightItalic.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-Medium.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-MediumItalic.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-Regular.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-SemiBold.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-Black.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-BlackItalic.ttf"
        - asset: "asset/fonts/Mulish/static/Mulish-Bold.ttf"

    - family: Nunito
      fonts:
        - asset: "asset/fonts/Nunito/static/Nunito-ExtraBoldItalic.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-ExtraLight.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-ExtraLightItalic.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-Italic.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-Light.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-LightItalic.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-Medium.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-MediumItalic.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-Regular.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-SemiBold.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-Black.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-BlackItalic.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-Bold.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-BoldItalic.ttf"
        - asset: "asset/fonts/Nunito/static/Nunito-ExtraBold.ttf"

    - family: Open_Sans
      fonts:
        - asset: "asset/fonts/Open_Sans/static/OpenSans_Condensed-Italic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_Condensed-Light.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_Condensed-LightItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_Condensed-Medium.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_Condensed-MediumItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_Condensed-Regular.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_Condensed-SemiBold.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_Condensed-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_SemiCondensed-Bold.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_SemiCondensed-BoldItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_SemiCondensed-ExtraBold.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_SemiCondensed-ExtraBoldItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_SemiCondensed-Italic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_SemiCondensed-Light.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_SemiCondensed-LightItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_SemiCondensed-Medium.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_SemiCondensed-MediumItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_SemiCondensed-Regular.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_SemiCondensed-SemiBold.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_SemiCondensed-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans-Bold.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans-BoldItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans-ExtraBold.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans-ExtraBoldItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans-Italic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans-Light.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans-LightItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans-Medium.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans-MediumItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans-Regular.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans-SemiBold.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_Condensed-Bold.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_Condensed-BoldItalic.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_Condensed-ExtraBold.ttf"
        - asset: "asset/fonts/Open_Sans/static/OpenSans_Condensed-ExtraBoldItalic.ttf"

    - family: Poppins
      fonts:
        - asset: "asset/fonts/Poppins/Poppins-Bold.ttf"
        - asset: "asset/fonts/Poppins/Poppins-BoldItalic.ttf"
        - asset: "asset/fonts/Poppins/Poppins-ExtraBold.ttf"
        - asset: "asset/fonts/Poppins/Poppins-ExtraBoldItalic.ttf"
        - asset: "asset/fonts/Poppins/Poppins-ExtraLight.ttf"
        - asset: "asset/fonts/Poppins/Poppins-ExtraLightItalic.ttf"
        - asset: "asset/fonts/Poppins/Poppins-Italic.ttf"
        - asset: "asset/fonts/Poppins/Poppins-Light.ttf"
        - asset: "asset/fonts/Poppins/Poppins-LightItalic.ttf"
        - asset: "asset/fonts/Poppins/Poppins-Medium.ttf"
        - asset: "asset/fonts/Poppins/Poppins-MediumItalic.ttf"
        - asset: "asset/fonts/Poppins/Poppins-Regular.ttf"
        - asset: "asset/fonts/Poppins/Poppins-SemiBold.ttf"
        - asset: "asset/fonts/Poppins/Poppins-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Poppins/Poppins-Thin.ttf"
        - asset: "asset/fonts/Poppins/Poppins-ThinItalic.ttf"
        - asset: "asset/fonts/Poppins/Poppins-Black.ttf"
        - asset: "asset/fonts/Poppins/Poppins-BlackItalic.ttf"

    - family: Raleway
      fonts:
        - asset: "asset/fonts/Raleway/static/Raleway-BoldItalic.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-ExtraBold.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-ExtraBoldItalic.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-ExtraLight.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-ExtraLightItalic.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-Italic.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-Light.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-LightItalic.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-Medium.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-MediumItalic.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-Regular.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-SemiBold.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-Thin.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-ThinItalic.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-Black.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-BlackItalic.ttf"
        - asset: "asset/fonts/Raleway/static/Raleway-Bold.ttf"

    - family: Roboto_Mono
      fonts:
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-Bold.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-BoldItalic.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-ExtraLight.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-ExtraLightItalic.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-Italic.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-Light.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-LightItalic.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-Medium.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-MediumItalic.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-Regular.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-SemiBold.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-Thin.ttf"
        - asset: "asset/fonts/Roboto_Mono/static/RobotoMono-ThinItalic.ttf"

    - family: Winky_Sans
      fonts:
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-Light.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-LightItalic.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-Medium.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-MediumItalic.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-Regular.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-SemiBold.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-SemiBoldItalic.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-Black.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-BlackItalic.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-Bold.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-BoldItalic.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-ExtraBold.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-ExtraBoldItalic.ttf"
        - asset: "asset/fonts/Winky_Sans/static/WinkySans-Italic.ttf"

  # To add asset to your application, add an asset section, like this:
  # asset:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding asset from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
